### ISSUE TITLE
Unable to get disk_dict working 

### ISSUE THREAD

**Issue by ajitbalan** [AWNystrom/DiskDict#3]
Hi Andrew,

I am using Python 3.5 and ran pip install disk_dict which was successful however when I try to import disk_dict i get the following error:

> > > import disk_dict
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/Users/foo/project/lib/python3.5/site-packages/disk_dict/**init**.py", line 1, in <module>
> > >     from disk_dict import DiskDict
> > > ImportError: cannot import name 'DiskDict'

I am using a virtualenv as well. I am not sure whats wrong, Am I missing something ? Any help is appreciated

Thanks

**Comment by AliShug** [comment]
Not the maintainer, but I think this package was designed to work with Python 2.7!

**Comment by AWNystrom** [comment]
Yeah, this was indeed written for Python 2.7. If there's interest I could get it working on 3.5. AliShug, did you encounter the same issue?

**Comment by AliShug** [comment]
@AWNystrom Yup, it screws up like this when imported on Python 3(.6 for me). I'm just screwing around with local storage, but if you want this package to gather interest it's probably worth supporting Python 3 👍
